name: DEV Environment - Suite Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Choice a browser to run the suite Web
        options:
        - Chrome
        - Firefox
        - Edge

jobs:
  build:
    runs-on: windows-latest
    name: Build and Run Web tests
    
    steps:
    - name: Checkout (including submodules and tags) 
      uses: actions/checkout@v4.1.1
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Set up JDK 19
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '19'
        distribution: 'temurin'
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
  
    - name: Run tests
      env:
        BROWSER: ${{ github.event.inputs.browser }}
      shell: bash
      run: |
        if [[ $BROWSER = "Chrome" ]]; then
          ./gradlew runStories -Pvividus.configuration.environments=dev \
                               -Pvividus.configuration.suites=web \
                               -Pvividus.configuration.profiles=web/desktop/chrome
        elif [[ $BROWSER = "Firefox" ]]; then
          ./gradlew runStories -Pvividus.configuration.environments=dev \
                               -Pvividus.configuration.suites=web \
                               -Pvividus.configuration.profiles=web/desktop/firefox
        elif [[ $BROWSER = "Edge" ]]; then
          ./gradlew runStories -Pvividus.configuration.environments=dev \
                               -Pvividus.configuration.suites=web \
                               -Pvividus.configuration.profiles=web/desktop/edge
        else
          ./gradlew runStories
        fi

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-web
        path: output/dev-web-report/allure-results-web
  
  generate_report:
    name: Generate Allure report
    runs-on: ubuntu-latest
    if: always()
    needs: [ build ]
    steps:
    - name: Download Artifacts 🔻
      uses: actions/download-artifact@v4
      id: download-report-web
      with:
        name: allure-results-web
        path: allure-results-web

    - name: Display downloaded files
      run: ls -R
      
    - name: Get Allure history
      uses: actions/checkout@v4.1.1
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Generate Allure Report with history
      uses: simple-elf/allure-report-action@v1.8
      if: always()
      id: allure-report-web
      with:
        allure_results: allure-results-web
        allure_report: allure-report-web
        allure_history: allure-history-web
        subfolder: dev-web
        keep_reports: 30

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v3.9.3
      if: always()
      with:
        personal_token: ${{ secrets.ACTION_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history-web
        keep_files: true
